POSTGRES_CONTRACTS_DB_URL: jdbc:postgresql://localhost:5432/contract_db
POSTGRES_CONTRACTS_DB_USERNAME: postgres
POSTGRES_CONTRACTS_DB_PASSWORD: 19032004
AUTH_JWT_TOKEN: 30faa058f27f690c7e9a098d54ebcfb3d8725bcb85ee7907a2d84c69622229e2
