spring:
  application:
    name:
      creating_contract

  datasource:
    url: ${POSTGRES_CONTRACTS_DB_URL}
    username: ${POSTGRES_CONTRACTS_DB_USERNAME}
    password: ${POSTGRES_CONTRACTS_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /api-docs

auth:
  enabled:
    true
  jwt:
    secret: ${AUTH_JWT_TOKEN}

management:
  tracing:
    sampling:
      probability: 1.0
  server:
    port: 8100
  endpoints:
    web:
      exposure:
        include: [ 'info','health','prometheus','loggers']
  endpoint:
    prometheus:
      access: read_only
  metrics:
    tags:
      application: ${spring.application.name} ${spring.profiles.active:}



